#ifndef DEMO_WIFI_CONFIG_H
#define DEMO_WIFI_CONFIG_H

#define WIFI_RECONNECT_TASK_NAME "wifi_reconnect"
#define WIFI_RECONNECT_TASK_PRIORITY democonfigDEMO_PRIORITY
#define WIFI_RECONNECT_TASK_STACK_SIZE democonfigDEMO_STACKSIZE

#define WIFI_RECONNECT_DELAY_MS 1000U

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#endif /* DEMO_WIFI_CONFIG_H */
